{
  imports = [
    ./adguard_home.nix
    ./anubis.nix
    ./caddy.nix
    ./db-gate.nix
    ./flaresolverr.nix
    ./forgejo.nix
    ./homepage-dashboard.nix
    ./immich.nix
    ./jellyfin.nix
    ./jellyseerr.nix
    ./pocket_id.nix
    ./samba.nix
    ./stirling-pdf.nix
    ./suwayomi.nix
    ./tiny_auth.nix
  ];
}
